server:
  port: 8081
spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/db_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: hocgin
    schema:
      - classpath:db/schema-maria.sql
    data:
      - classpath:db/data-maria.sql
    initialization-mode: always

mybatis-plus:
  global-config:
    refresh: true
logging:
  level:
#    in.hocg: debug
    com.baomidou.mybatisplus: debug