#server:
#  port: 8081
spring:
  datasource:
    url: jdbc:mariadb://mysql.localhost:3306/db_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: hocgin
mybatis-plus:
  global-config:
    refresh: true
logging:
  level:
#    org.springframework: debug
    in.hocg: debug