spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    druid:
      validation-query: select '1'
  session:
    store-type: none
  messages:
    basename: i18n/messages
    encoding: UTF-8
  profiles:
    active: dev
  #######################
  #                 _ _
  # _ __ ___   __ _(_) |
  #| '_ ` _ \ / _` | | |
  #| | | | | | (_| | | |
  #|_| |_| |_|\__,_|_|_|
  #######################
  mail:
    host: smtp.163.com
    username: 13600747016@163.com
    # 此处 password 为授权码
    password: 123456qA
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.debug: true

###########################
#        AliYun OSS 开发参数
# https://www.aliyun.com/product/oss?spm=5176.8142029.388261.574.e9396d3eKg8j7h
###########################
ali:
  oss:
    enabled: true
    endpoint: http://oss-cn-beijing.aliyuncs.com
    secret-access: WTNAERBXO7DQOLXILIHjx8NZCzdRmw
    access-key: LTAIMo7TgRT1ZohX

mybatis-plus:
  mapper-locations: classpath*:/in/hocg/mybatis/module/*/mapper/xml/*Mapper.xml
  typeAliasesPackage: in.hocg.entity
  typeEnumsPackage: in.hocg.*.*
  global-config:
    db-config:
      db-type: mariadb
      id-type: id_worker
      field-strategy: not_empty
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'

server:
  port: 8080