#server:
#  port: 8081
spring:
  datasource:
    url: jdbc:mariadb://mysql.localhost:3306/db_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: hocgin
    schema:
    - classpath:db/schema-maria.sql
    data:
    - classpath:db/data-maria.sql
    initialization-mode: always
logging:
  level:
#    root: debug
#    org.springframework: debug
    com.baomidou.mybatisplus: debug
    in.hocg: debug


scaffold:
  anti-replay:
    ignore-url:
    - /login
    enabled: false
security.token.filter.secret: YourSecretNeedsToBeAtLeast256BitsLong
