spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    druid:
      validation-query: select '1'
  session:
    store-type: none
  profiles:
    active: dev
  #######################
  #                 _ _
  # _ __ ___   __ _(_) |
  #| '_ ` _ \ / _` | | |
  #| | | | | | (_| | | |
  #|_| |_| |_|\__,_|_|_|
  #######################
  mail:
    host: smtp.163.com
    username: 13600747016@163.com
    # 此处 password 为授权码
    password: 123456qA
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.debug: true
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  typeAliasesPackage: in.hocg.mybatis.*.entity.*
  typeEnumsPackage: in.hocg.mybatis.*.enums.*
  global-config:
    db-config:
      db-type: mariadb
      id-type: id_worker
      field-strategy: not_empty
      table-underline: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
server:
  port: 8080