#server:
#  port: 8081
spring:
  datasource:
    url: jdbc:mariadb://mysql.localhost:3306/db_test?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: hocgin
    schema:
    - classpath:db/schema-maria.sql
    data:
    - classpath:db/data-maria.sql
    initialization-mode: always
  redis:
    host: 127.0.0.1
#    swagger
  swagger:
    enabled: true
    group:
      account:
        title: 账号相关
        description: 账号相关API
        path-regex: /api/v1/account/.*
        path-mapping: /
logging:
  level:
    #    root: debug
    #    org.springframework: debug
    com.baomidou.mybatisplus: debug
    in.hocg: debug


###########################
#        AliYun OSS 开发参数
# https://www.aliyun.com/product/oss?spm=5176.8142029.388261.574.e9396d3eKg8j7h
###########################
oss:
  enabled: true
  type: aliyun
  ali-yun:
    endpoint: http://oss-cn-beijing.aliyuncs.com
    secret-access: WTNAERBXO7DQOLXILIHjx8NZCzdRmw
    access-key: LTAIMo7TgRT1ZohX

################
# 自定义功能开关 #
###############
scaffold:
  # 防重放攻击
  anti-replay:
    ignore-url:
    - /login
    enabled: false
security.token.filter.secret: YourSecretNeedsToBeAtLeast256BitsLong


