spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    druid:
      validation-query: select '1'
  session:
    store-type: none
  profiles:
    active: dev
  #######################
  #                 _ _
  # _ __ ___   __ _(_) |
  #| '_ ` _ \ / _` | | |
  #| | | | | | (_| | | |
  #|_| |_| |_|\__,_|_|_|
  #######################
  mail:
    host: smtp.163.com
    username: 13600747016@163.com
    # 此处 password 为授权码
    password: 123456qA
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.debug: true
mybatis-plus:
  # 开包含多个路径, 用,分隔(*任意一个, **任意多个)
  mapper-locations: classpath*:/mapper/**/*Mapper.xml
  # 开包含多个路径, 用,分隔(*任意一个, **任意多个)
  typeAliasesPackage: in.hocg.mybatis.**.entity**
  # 开包含多个路径, 用,分隔(*任意一个, **任意多个)
  typeEnumsPackage: in.hocg.mybatis.enums**
  global-config:
    db-config:
      db-type: mariadb
      id-type: uuid
      field-strategy: not_empty
      table-underline: true
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'
################
# 自定义功能开关 #
###############
scaffold:
  # 防重放攻击
  anti-replay:
    ignore-url:
    - /login
    enabled: true
server:
  port: 8080
